### ISSUE TITLE
Decide on Editorial Team

### ISSUE THREAD

**Issue by Silvertrousers** [SOMAS2021/SOMAS-Final-Report#14]
This is the group of people responsible for looking at all PR's, proofreading them, and suggesting changes. The team should be small to allow for a consistent writing style throughout the report.

**Comment by jzzheng22** [comment]
Would say minimum of one person from each team - for Team 5, @daryllimyt has volunteered.

**Comment by tomeaton17** [comment]
I would be happy to do this. I am very familiar with LaTeX so happy to help with typesetting as well.

**Comment by fds101** [comment]
Seems like this has been solved so I'll close it now.
